### ISSUE TITLE
DISCUSS: Show watermark files only? Convert from quicktime?

### ISSUE THREAD

**Issue by afred** [WGBH/stock-sales-2#179]
@Muraszko @AlisonCSmith @mccalluc 

Two issues here:

### 1. Sony Ci Proxies are roughly the same size as SD originals.

If this implies that they are also roughtly the same quality, then that's a problem, b/c people can download for free (with a little effort) the thing we're trying to license.

One solution would be to only allow playback of watermarked videos everywhere. This seems to be an acceptable standard among competitors.

however.. this brings us to issue number 2...

### 2. Watermarked proxies from current site do not play as-is.

@mccalluc reports that attempting to play them prompts you to install the quicktime player.

This is reminiscent of the issue we had with Openvault, where our solutions was to convert as much as we could to webm, which is adequately browser friendly. Not sure what kind of tricks the current site is using to get around this.

First we should confirm this is what is actually going on, i.e. the videos being served are being recognized by browsers as requiring the quicktime plugin.

If that's the case, then we're looking at converting all of the watermarked files to webm before they are usable. And if we're doing this, then we may be able to throw money at a big EC2 box in AWS to do it faster than we could do in house. Just a thought.

**Comment by Muraszko** [comment]
@afred @mccalluc @AlisonCSmith 
I don't think 1. is true. SD clips are 720x480 or 640x480.  Ci creates 480x360 and 360x270 versions for 720x480 source.
Chuck, you said you would try having the clip playback use the 360x270 small proxy version, but scaled up to whatever the player size was on the page.  Is that working for you?  I only get errors on the demo site when I try.

For 2. the watermarked videos are in a Motion Jpeg codec Quicktime MOV wrapper.  It's not uncommon, but not really a format people use for streaming video.  The watermarked videos are intended to be delivered only as file downloads for users to view and create rough edits in their video editing programs, they are fine.  There is no need to convert these to webm because they are download only.

**Comment by Muraszko** [comment]
From developer documentation:
‘video-3g’	480x270, 200kbps, h264 codec, mp4 container.
‘video-sd’	640x360, 560kbps, h264 codec, mp4 container.
‘video-sdplus’	960x540, 1650kbps, h264 codec, mp4 container.

**Comment by mccalluc** [comment]
3g proxies are deployed: a little grainy, but good enough.
