### ISSUE TITLE
Add a "loading" gif on hover of search result videos in the second or two before playback

### ISSUE THREAD

**Issue by afred** [WGBH/stock-sales-2#226]
We are downloading the video on mouse over, which can take a second or two. We should give some instantaneous feedback that says "Hey, something is loading, wait a second". This can be done with by overlaying some kind of gif (spinning, loading, etc.), and maybe grayed-out the video's poster a little bit.

**Comment by mccalluc** [comment]
@afred: Before going too far down this road, maybe we should just make the videos load faster? When I first did this, and thought the video proxy URLS, like the images, would last a year at least, we didn't need to make that extra round trip to the API, and then the redirect: We just put the actual video URL in the <video> element, and that was that.

- Could imagine we maintain an in-memory cache of all video URLs, and every page request has an AJAX hey-do-we-need-to-update-the-cache, which most of the time does nothing, but sometimes sets off 20 500-at-a-time calls to get the freshest Media URLs.
- Or, Could imagine an AJAX call just on search results pages. We would still have our media redirect URLs, but instead of hitting the Ci API for each one, we would do it once on page load.

**Comment by afred** [comment]
per conversation just now... sounds good. Closing this in favor of a caching approach. Reminder to ask Sony about whether we have api call limits
