### ISSUE TITLE
Right align contact info in header with outer margin

### ISSUE THREAD

**Issue by afred** [WGBH/stock-sales-2#278]
**Done when** contact info in header is aligned with outer margin

**Comment by mccalluc** [comment]
just the phone + email line? Not the header links? logo on the left? or the footer stuff? This is coming from bootstrap, I think, so I'm not eager to start overriding it needlessly.

**Comment by afred** [comment]
@lwei wouldn't it make more sense to align the email+phone with other right-aligned content, as opposed to the outermost margin of the page. Doing the latter would make [this page](http://demo.wgbhstocksales.org/about/research) look weird.

**Comment by lwei** [comment]
@afred the email+phone and the other nav links below should be right aligned. I initially thought they should be pushed to the right outer margin, but now looking at the mobile phone view, where the dark blue background goes away and the content margin becomes the outer margin... I think it makes sense to keep top and bottom nav links aligned with the content margins instead of the outermost margins.

**Comment by mccalluc** [comment]
So it sounds like the status quo is fine? Closing. @afred, correct me if I'm mistaken.
